#cloud-config

package_upgrade: true

users:
  - name: username
    shell: /bin/bash
    sudo: ALL=(ALL) NOPASSWD:ALL
    passwd: "$6$XW1iVscgtVUuEZeZ$XXiZROggD.K/OXfSX5UgmDAX6S7i1bA/sIbELm5Xry9dk9O03dge7V7LmcinUgntsp6NgKRe6Gnsml8fUMuca0"
    lock_passwd: false

packages:
  - azure-cli
  - docker
  - git
  - google-cloud-cli
  - graphviz
  - httpd
  - mysql
  - unzip
  - wget

yum_repos:
  azure-cli:
    baseurl: "https://packages.microsoft.com/yumrepos/azure-cli"
    name: azure-cli
    enabled: true
    gpgcheck: true
    gpgkey: "https://packages.microsoft.com/keys/microsoft.asc"
  google-cloud-cli:
    baseurl: "https://packages.cloud.google.com/yum/repos/cloud-sdk-el8-x86_64"
    name: google-cloud-cli
    enabled: true
    gpgcheck: true
    gpgkey:
      - "https://packages.cloud.google.com/yum/doc/yum-key.gpg"
      - "https://packages.cloud.google.com/yum/doc/rpm-package-key.gpg"

runcmd:
  - sed -i 's/PasswordAuthentication no/PasswordAuthentication yes/' /etc/ssh/sshd_config
  - systemctl restart sshd
  - systemctl --now enable docker
  - curl https://releases.hashicorp.com/terraform/1.1.7/terraform_1.1.7_linux_amd64.zip -o terraform.zip
  - unzip terraform.zip -d /usr/local/bin
  - chmod 755 /usr/local/bin/terraform
  - wget https://github.com/gruntwork-io/terragrunt/releases/download/v0.36.3/terragrunt_linux_amd64
  - mv terragrunt_linux_amd64 /usr/local/bin/terragrunt
  - chmod 755 /usr/local/bin/terragrunt
  - curl https://releases.hashicorp.com/sentinel/0.18.7/sentinel_0.18.7_linux_amd64.zip -o sentinel.zip
  - unzip sentinel.zip -d /usr/local/bin
  - chmod 755 /usr/local/bin/sentinel
